### PR TITLE
Feat: Nuxt 3 Adapter

### PR DESCRIPTION
**Pull request by Bahnasawy**

### CODE REVIEW

**Comment by mihai1voicescu** [comment]
Any ETA on this? Maybe it would help to add some Reviewers.

**Comment by Bahnasawy** [comment]
I may be a little new at this, but I can't seem to add @jlalmes as a reviewer, am I missing something?

**Review by jlalmes — APPROVED** [review]
Whoops accidental, looking now :)

**Review by jlalmes — APPROVED** [review]

**Comment by jlalmes** [comment]
Available in `trpc-openapi@1.2.0`

**Comment by Bahnasawy** [comment]
Glad it's finally merged!! Awesome work on this library so far 👏👏

**Comment by u007** [comment]
didnt work for me,
my code:
```
export const loginByApiToken = publicProcedure.meta({ openapi: { method: 'POST', path: '/auth/token' } })
  .input(z.object({
    token: z.string().min(1),
  })).mutation(
    async ({ input: { token }, ctx }) => {
      const config = useRuntimeConfig()

```

i tried calling POST /api/auth/token and /auth/token, getting 404
could it be that ive actual /api/auth on server api end?

**Comment by u007** [comment]
okay i followed the example for nuxt and it works, but ive to set a different context for openapi as nuxt h3 api uses:
```
export async function createContext ({ node: { req, res } }: H3Event) {
  const requestId = uuid()
  ```
vs openapi
```
export const createOpenAPIContext = async ({
  req,
  res,
}: {
  req: IncomingMessage;
  res: ServerResponse<IncomingMessage>;
}) => {
```

**Pull request merged**
