### PR TITLE
OpenAPI Error Response should be called `error`, not `default`

### PR DESCRIPTION
**Pull request by shaun-scale**
As you port your tRPC OpenAPI spec files to documentation generators, it looks like the default response is the error one. I think it would be more clear to just call this `error` vs. `default`. 

Example in the popular API Docs service, Readme.

### CODE REVIEW

**Comment by shaun-scale** [comment]
Ok, so I tried this and now understand that `default` is a reserved keyword that can't be changed to `error` - I suppose the next question, then, is how to enumerate error responses well. Let me review some more.

**Comment by mattrossman** [comment]
@shaun-scale I'm interested in this as well, please report back if you figure out how to enumerate error responses.

**Comment by shaun-scale** [comment]
For now, I mapped out to a generic `400` error, this is most certainly _NOT_ the real solve, but it looks marginally better than default...

We have some post processing code that tries to clean up, order, etc. our OAS specs

The relevant bit is below

```
const spec = generateOpenApiDocument(publicRouter, {
  title: '<APP> API',
  version: '1.0.0',
  baseUrl: BASE_URL,
});

// Post-Process Generated Spec:
// - Remove 'mutation.' prefix from operationIds
// - Remove 'query.' prefix from operationIds
// - Remove deprecated endpoints
// - Sort paths and methods

for (const [path, pathValue] of Object.entries(spec.paths)) {
  if (!pathValue) {
    continue;
  }

  let operationId;
  for (const method of ['get', 'post', 'delete', 'put', 'patch']) {
    operationId = pathValue?.[method]?.operationId;
    if (!operationId) {
      continue;
    }
    if (operationId.includes('deprecated')) {
      delete (spec as OpenAPIV3.Document).paths[path];
      continue;
    }
    pathValue[method].operationId =
      method === 'get' ? operationId.split('query.')[1] : operationId.split('mutation.')[1];

    // Update the error response schema to be generally put in a 400 status code
    // TODO: Set actual errors with status codes
    if (pathValue[method].responses?.['default']) {
      pathValue[method].responses['400'] = pathValue[method].responses['default'];
      delete pathValue[method].responses['default'];
    }

    // TODO: Add `descriptions` to the error fields
  }
}
```

**Comment by jlalmes** [comment]
Whoops - accidentally re-opened, let me know if you find a elegant solution to this!

**Pull request closed without merging**
