### PR TITLE
Feat: Fastify adapter

### PR DESCRIPTION
**Pull request by jlalmes**

### CODE REVIEW

**Review by ckt1031 — DISMISSED** [review]

**Review by SeanCassiere — DISMISSED** [review]
Not sure how you resolve the package-lock stuff, but with local testing it works.

**Comment by sylent3524** [comment]
This can be merged into here, then from here into master.

https://github.com/jlalmes/trpc-openapi/pull/254

_Should I have done it directly into master?_

**Comment by sylent3524** [comment]
Here are the commands I ran to fix it:
`gh pr checkout 177 && git fetch origin master && git merge origin/master`
`rm package-lock.json`
_manually merged dependencies in package.json_
`npm i --package-lock-only`

final testing: 
`npm i && npm run test`

**Comment by nahtnam** [comment]
Would love to use this! Anything blocking merge and release?

**Comment by cacode-euan** [comment]
Hi guys, is there anything that needs doing before this can be merged? 🙂

**Comment by Asher-JH** [comment]
Would be great to use this soon, anything blocking the merge still?

**Comment by Mikaleb** [comment]
Nothing new ?

**Comment by sylent3524** [comment]
Still waiting for [my pr](https://github.com/jlalmes/trpc-openapi/pull/254) to be accepted😴

In the meantime, you could just take [this file from the pr](https://github.com/jlalmes/trpc-openapi/pull/177/files#diff-5c34905418dcc2dc32657cd9a8c18631f3bd2d7f1ba286c99a05394742442d97) and put it in your project to get the adapter working.

**Comment by productdevbook** [comment]
when pr merge ?

**Comment by joshuaja** [comment]
@jlalmes what's the ETA on the release for this? I could definitely use this in my Fastify project.

**Review by jlalmes — COMMENTED** [review]
Thank you to all contributors for pushing this PR over the line. Sorry for the delay in getting it merged!

**Comment by jlalmes** [comment]
Available in `trpc-openapi@1.2.0`

**Pull request merged**
